### PR TITLE
PR partially addressing issue Geosyntec/python-tidegates#13

### PR DESCRIPTION
**Pull request by HEdingfield**
I made the following changes to the code:
-Fixed an apparent error in pytidegate.pyt where a function returned tidegate.assess_impact instead of tidegates.assess_impact.
-Removed unused import statements.
-Added numpy as a requirement in setup.py.
-Cleaned up some spelling errors and formatting in the README.
-Fixed some random typos.

All tests ran successfully, with the following exceptions:
- test_unlicensed_extension:

```
Failure
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.2\lib\unittest\case.py", line 327, in run
    testMethod()
  File "C:\Python27\ArcGIS10.2\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\ArcGIS10.2\lib\site-packages\nose\tools\nontrivial.py", line 67, in newfunc
    raise AssertionError(message)
AssertionError: test_unlicensed_extension() did not raise RuntimeError
```
- test_clip_dem_to_zones was giving me trouble because of the line `arcpy.management.Delete(raster)`. It had something to do with not being able to delete the file while it was being accessed by another program. I temporarily commented that out, and the test ran fine.

Finally, I attempted to test the toolbox in ArcMap 10.2 but repeatedly encountered this error:

```
Traceback (most recent call last): File "", line 82, in updateParameters File "", line 118, in tidegate_column File "", line 54, in _set_parameter_dependency AttributeError: 'NoneType' object has no attribute 'name' 
```

I also noted that **there doesn't appear to be an input for the DEM**.

### CODE REVIEW

**Comment by phobson** [comment]
Can you submit this against upstream and raise the appropriate items as issues there?

**Comment by HEdingfield** [comment]
@phobson sorry, I'm out today and not sure if you wanted me to PR my branch directly against upstream master? That seems a bit dangerous to me. Also looks like you've worked on this branch on your end since my PR. Not exactly sure how you want to resolve, but it's probably safest that you handle it.

I went ahead and raised Geosyntec/python-tidegates#18 and Geosyntec/python-tidegates#19 as requested.

**Comment by phobson** [comment]
> That seems a bit dangerous to me

It's not. That's the basis of gitwash and github-flow
http://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html
https://guides.github.com/introduction/flow/

Thanks for the PRs.

Closing in favor of #18 and #19

**Comment by HEdingfield** [comment]
I recommend we still implement the changes to README.md in the PR (and setup.py, but that's your call).

**Comment by phobson** [comment]
That'd be good. I like to separate test requirements from run requirements. So in that sense, the rethe requirements are numpy and arcpy. 

—

**Pull request closed without merging**
